[env:m5stickc-plus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.f_cpu = 160000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<main.cpp> +<ble_bridge.cpp>
lib_deps =
    m5stack/M5Unified @ ^0.2.0
    bblanchon/ArduinoJson @ ^7.0.0

[env:m5stick-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DM5STICK_S3=1
    -DAUDIO_RATE=16000
upload_resetmethod = usb
build_src_filter = +<main.cpp> +<ble_bridge.cpp>
lib_deps =
    m5stack/M5Unified @ ^0.2.0
    bblanchon/ArduinoJson @ ^7.0.0

[env:dualkey-minecraft]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
upload_resetmethod = usb
build_src_filter = +<dualkey_minecraft.cpp>
lib_deps =
    m5stack/M5Chain
