[env:m5stickc-plus]
platform = espressif32
board = m5stick-c
framework = arduino
lib_deps =
    m5stack/M5StickCPlus
    adafruit/Adafruit MLX90614 Library
    adafruit/Adafruit BusIO
monitor_speed = 115200
